# Generated by Django 4.2.4 on 2023-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='birth_data',
            field=models.DateTimeField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_data',
            field=models.DateTimeField(verbose_name='expiration date'),
        ),
    ]
