# Generated by Django 4.2.4 on 2023-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_birth_data_alter_card_expiration_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='birth_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
